apiVersion: v1
kind: ReplicationController
metadata:
  name: myjava-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
        - name: mycontainer
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080
